### PR TITLE
Fix unreadable qr code and shadows

### PR DESCRIPTION
**Pull request by mijorus**
this works for me

### CODE REVIEW

**Comment by lucianomurr** [comment]
Maybe I've to fix also the pipeline for PR like this...

**Comment by mijorus** [comment]
I'm sorry I should have splitted the UI changes from the QR code fix

**Comment by lucianomurr** [comment]
could you try to apply the same change of this PR => #45  here

**Comment by mijorus** [comment]
umh... `pull_request_target` should fix this, but I'm worried about security implications

**Comment by lucianomurr** [comment]
> umh... `pull_request_target` should fix this, but I'm worried about security implications

what do you mean?

**Comment by mijorus** [comment]
> > umh... `pull_request_target` should fix this, but I'm worried about security implications
> 
> what do you mean?

why do you think it is failing?

**Comment by lucianomurr** [comment]
> > > umh... `pull_request_target` should fix this, but I'm worried about security implications
> > 
> > 
> > what do you mean?
> 
> why do you think it is failing?

Sorry for the late reply... I mean, the pipeline that tries to build and deploy the feature branch fails... and the merge is blocked by this.

**Comment by mijorus** [comment]
> > > > umh... `pull_request_target` should fix this, but I'm worried about security implications
> > > 
> > > 
> > > what do you mean?
> > 
> > 
> > why do you think it is failing?
> 
> Sorry for the late reply... I mean, the pipeline that tries to build and deploy the feature branch fails... and the merge is blocked by this.
> 
> We can have a call if you want!

DM me on LinkedIn

**Pull request merged**
