### PR TITLE
Winner modal

### LINKED ISSUE #57: The admin page should Emphasize the winner! 🥳
- Modal with the name and the ticket ID of the winner!
 - Confetti animation: https://github.com/catdad/canvas-confetti

### PR DESCRIPTION
**Pull request by lucianomurr**
close #57

### CODE REVIEW

**Comment by lucianomurr** [comment]
@AlessioMonterosso @mijorus 
what do you think?

Screenshot 2023-05-06 at 15 56 14

**Comment by AlessioMonterosso** [comment]
I like it

**Review by AlessioMonterosso — APPROVED** [review]

**Comment by lucianomurr** [comment]
> I like it

even with fireworks!

Screenshot 2023-05-06 at 16 45 15

**Comment by mijorus** [comment]
> @AlessioMonterosso @mijorus what do you think?
> 
> Screenshot 2023-05-06 at 15 57 23

Looks nice to me! Maybe I would just add a close button somewhere, if it doesn't take much work

**Pull request merged**
